### ISSUE TITLE
ExponentialVertex Arguments

### ISSUE THREAD

**Issue by michael-adcock** [improbable-research/keanu#101]
Hi,

When I use an exponential vertex I would normally expect to have to input a single parameter (Lambda). However your Exponential Vertex constructor takes two arguments. The issue is that these arguments are named 'a' and 'b' so it is not clear what these arguments relate to. Clear naming and docs would solve the issue nicley.

Thanks,
Mike

**Comment by gordoncaleb** [comment]
This is indeed strange. One parameter is a horizontal shift and the other is your usual lambda, but it's definitely not clear which is which. We'll rename the parameters to something more appropriate and  provide a one parameter constructor that takes just your usual lambda. We'll let you know when the code has been merged/released and ready to be used. 

Thanks Mike!

**Comment by gordoncaleb** [comment]
Hi Mike,

The location hyper-parameter has been removed in Keanu 0.0.11. That leaves only the usual lambda as a parameter for the Exponential distribution.
