### ISSUE TITLE
Allow some sort of access to internal nd4j reprensentation of `DoubleTensor`

### ISSUE THREAD

**Issue by chris-major-improbable** [improbable-research/keanu#137]
**I'm trying to convert some existing `nd4j` code into a keanu vertex.**
As the existing code expects an `INDArray` as input, I'd like to convert the `DoubleTensor` into one - I an see it's internal representation is the same, but can't access it as it's private.

**Could we have an `getInternalRepresentation` function on the `DoubleTensor`**
This would allow:
```java
if ( tensor instanceof Nd4jDoubleTensor){
  Nd4jDoubleTensor internal = (Nd4jDoubleTensor)internal;
  INDArray represntation = internal.getInternalRepresentation();
  // do something efficient
}else{
  // do something inefficient
}
```
the implementation is fairly straightforward
```java
public INDArray getInternalRepresentation(){
    return tensor;
}
```

**Alternatives**
This isn't a deal breaker - but copying via the CPU would impact speed significantly.
Obviously this risks unexpected access to the backing data for a tensor - if this is a blocked then maybe a function that would allow copying into another `INDArray` would ensure it's duplicated but not changed.

I've raised a PR for this change at #129

**Comment by gordoncaleb** [comment]
ND4J is a implementation detail in Keanu (despite the class name clearly stating what's going on). Ideally, you should be able to convert any ND4J code to equivalent Keanu code, but if you can't then we should raise those as feature requests and get them in Keanu. I'd imagine any feature request coming from this sort of thing would be very easy to implement considering most of the tensor classes are backed by the ND4J INDArray.

**Comment by chris-major-improbable** [comment]
That's true - but there's a huge user cost in rewriting existing ND4J code into keanu specific tensors - which also limits it's use in other contexts. Worse, it makes it impossible to effectively use a third party ND4J implementation within a vertex.

While these wouldn't be good long term solutions (as the internal keanu implementation may change) it would potentially accelerate use.

**Comment by GeorgeNash** [comment]
Closing this issue as we're going to cover any feature requests and not expose the underlying tensor.
