### ISSUE TITLE
Extended function on DoubleTensor

### ISSUE THREAD

**Issue by chris-major-improbable** [improbable-research/keanu#138]
**I'm trying to use `DoubleTesor` and feel it needs these functions:**
* `equalsWithEps`
This would allow the comparison between two `DoubleTensor`s with a specified epsilon.
* `zero`
This would set all elements in a `DoubleTensor` to 0. This may be a special case of a more general `setAll` function.

**Comment by chris-major-improbable** [comment]
Sugested implementation is in a PR #139

**Comment by GeorgeNash** [comment]
Closing as PR has been merged and released.
