### ISSUE TITLE
Exponential Vertex with Non-Tensor Hyper-parameters doesn't handle Tensor dLogProb correctly

### ISSUE THREAD

**Issue by christophernorth** [improbable-research/keanu#183]
**Describe the bug**
The Exponential Vertex is lacking a test similar to matchesKnownDerivativeLogDensityOfVector.  When added, the test fails.  This is because some of the partial derivatives only generate a Scalar (due to the initial shape of the hyper-parameters) instead of the expected Tensor.

**To Reproduce**
Create an exponential vertex with scalar hyper-parameters and then retrieve logProb for a vector of Values - incorrect values will be returned.

**Expected behavior**
We'd expect a sum for the dLogProb across the full tensor, but instead you simply receive the value for the first entry.

**Comment by GeorgeNash** [comment]
Great find - thanks for fixing this.

**Comment by GeorgeNash** [comment]
Approved your PR - feel free to merge :)
