### ISSUE TITLE
DirichletVertex as input to CategoricalVertex

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#185]
In order to learn the probabilities associated with categories in a `CategoricalVertex` it would be really useful to supply a Dirichlet distribution as a prior. This is used in Hidden Markov Models for example. ($x_{t=1..t}$ in https://en.wikipedia.org/wiki/Hidden_Markov_model#Examples)

The constructor could look something like this:
```
double concentration = 0.5;
DoubleVertex dirichlet = new DirichletVertex(new int[]{10}, concentration);
CategoricalVertex categorical = new CategoricalVertex<Integer>(dirichlet)
```
which would create a categorical distribution over 10 categories.

**Comment by johannespetrat** [comment]
The way I implemented this at the moment is 
```
private Map<Integer, DoubleVertex> dirichletToMap(DirichletVertex vertex){
        Map<Integer, DoubleVertex> probabilityMap = new HashMap<>();
        for (int i = 0; i < nStates; i++) {
            probabilityMap.put(i, new TakeVertex(vertex, 0, i));
        }
        return probabilityMap;
    }
```
where `nStates is the number of categories in the Dirichlet. Could be obtained using something like this
```vertex.sample().getLength();```

**Comment by GeorgeNash** [comment]
I like this a lot. I'll raise a JIRA ticket. Do you want to raise your own PR with a new constructor on `Categorical` that takes a `DirichletVertex`? Your code looks good - it'll just need a few tests.

**Comment by johannespetrat** [comment]
I can have a go at it. I already implemented the vertex and only need to add a few more tests.
