### ISSUE TITLE
DoubleTensor.linspace creates float values, not double

### ISSUE THREAD

**Issue by robertperrotta** [improbable-research/keanu#186]
The ND4J tensor within the DoubleTensor returned by DoubleTensor.linspace has contents of type FloatBuffer, not DoubleBuffer.

DoubleTensor.linspace(0.0, 1.0, 101)

**Comment by GeorgeNash** [comment]
Great spot. Raised a PR to fix this: https://github.com/improbable-research/keanu/pull/195

**Comment by GeorgeNash** [comment]
PR closed
