### ISSUE TITLE
Can't observe an IntegerTensor in CategoricalVertex

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#188]
It would be nice to add functionality to observe multiple values in an `IntegerTensor` for a `CategoricalVertex` to infer the probabilities of the categories.

**Comment by icantsayrural** [comment]
Added a new feature for observing multiple values in a tensor for a `CategoricalVertex`. When instantiating a categorical vertex, you will now need to also specify the tensor type in the type parameter section (e.g. `new CategoricalVertex<Integer, IntegerTensor>(selectableValues)`.
