### ISSUE TITLE
NetworkSamples streaming never updates network state

### ISSUE THREAD

**Issue by robertperrotta** [improbable-research/keanu#190]
`networkSamples.generate(N)` does not produce the same output as `networkSamples.stream().limit(N).toList()` For `MetropolisHastings`.

I believe the problem is that in `MetropolisHastings.java` lines 317 - 146:

```java
        @Override
        public void sample(Map<Long, List<?>> samplesByVertex) {
            step();
            takeSamples(samplesByVertex, verticesToSampleFrom);
        }

        @Override
        public NetworkState sample() {
            return new SimpleNetworkState(takeSample(verticesToSampleFrom));
        }
```

the first method (called by `generate(N)`) calls `step()` before `takeSamples` but the second doesn't.

**Comment by christophernorth** [comment]
Good spot - we'll work on getting this sorted.

**Comment by christophernorth** [comment]
Will make it out as part of the next release - look out for 0.0.13!
