### ISSUE TITLE
Observing a BoolVertex flattens it into a row vector (shape is lost)

### ISSUE THREAD

**Issue by stefano-romano** [improbable-research/keanu#194]
See this line: https://github.com/improbable-research/keanu/blob/f02a8ecaa8c25bbdfba0dc2f3ac871bc98f24572/keanu-project/src/main/java/io/improbable/keanu/vertices/bool/BoolVertex.java#L81

For example:
```
DoubleTensor probs = DoubleTensor.create(new double[] {0.5, 0.5}, new int[] {2, 1});
BoolVertex outcomes = new BernoulliVertex(new ConstantDoubleVertex(probs));
System.out.println(String.format("%s %s", outcomes.getShape()[0], outcomes.getShape()[1]));
// 2 1
outcomes.observe(new boolean[] {true, false});
System.out.println(String.format("%s %s", outcomes.getShape()[0], outcomes.getShape()[1]));
// 1 2
```
Not sure if this is limited to boolean vertices or general.
More generally, I think it'd make sense to be able to observe a tensor (of the same shape as the vertex) rather than a flat array.

**Comment by GeorgeNash** [comment]
Yeah that doesn't look right. I think if you're observing values on a tensor vertex, you should be given the choice to observe with a flat array or with a tensor of a known shape. Will raise a ticket to add this in.

**Comment by GeorgeNash** [comment]
Raised a PR for this: https://github.com/improbable-research/keanu/pull/196
