### ISSUE TITLE
`.transpose()` and `.reshape()` for vertices?

### ISSUE THREAD

**Issue by stefano-romano** [improbable-research/keanu#201]
I'm sure these are part of the plan, dropping this here as a reminder :)

**Comment by GeorgeNash** [comment]
Like that a lot - let me raise a ticket and get it underway

**Comment by GeorgeNash** [comment]
Raised a PR for reshape, transpose will take a little more work. Will keep this open and raise a ticket for transpose.

Reshape: https://github.com/improbable-research/keanu/pull/204

**Comment by christophernorth** [comment]
Transpose is a subset of the functionality provided by permute.

#451 fixes this.
