### ISSUE TITLE
`MinimumVertex` and `MaximumVertex`

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#239]
In one of my applications of Keanu I have found that a vertex calculating the minimum of two input vertices would be really helpful. This could also be used to create upper or lower bounds of vertices.

A `MinimumVertex` would likely just use `if` or `lessThanOrEqual` under the hood, but having this as a designated vertex would provide a nice layer of abstraction.

**Comment by GeorgeNash** [comment]
PR merged - closing.
