### ISSUE TITLE
Why Java?

### ISSUE THREAD

**Issue by springcoil** [improbable-research/keanu#253]
Hi guys,
I've just a random question - why Java? I understand why you'd like to use the JVM - but why not Clojure or Scala?

**Comment by gordoncaleb** [comment]
Hello,
Good question! For us, Keanu is part of something much bigger that we have in mind for the future. For those plans, using the JVM makes a lot of sense (as you have already pointed out). The idea is to build the core of it in plain old Java and have the more fun JVM languages layered on top. Currently, Kotlin is the only other JVM language we see being supported but it would be easy enough to add others (like Scala) in the future. The real question is why not Python first. We're working right now to add first class support for Python and go down a similar route that Spark went with PySpark.
