### ISSUE TITLE
getVertices on BayesNet

### ISSUE THREAD

**Issue by wesleyw72** [improbable-research/keanu#307]
Trying to get the vertices within a BayesNet to calculate metrics on the graph. There currently isn't an  exposed method on BayesNet to get all of the vertices. Can the private getVertices method be made public?

**Comment by GeorgeNash** [comment]
Short answer - no! We've hidden that due to users having the ability to create a bayes net and then mutate it at later (add vertices / observations etc). We're currently discussing whether this should be locked down or mutable......For now you can use `getConnectedGraph().size()`.

**Comment by wesleyw72** [comment]
This question was raised mainly for getting the vertex count of a BayesNet. This is now possible in `0.0.16` using `getVertexCount()` on a `BayesianNetwork` so closing this issue.
