### ISSUE TITLE
Getting the Keanu version

### ISSUE THREAD

**Issue by wesleyw72** [improbable-research/keanu#309]
Trying to record metrics of particular runs of a model. It would be nice to associate them with a specific Keanu version. For example, plotting the execution time of a model against the Keanu version.

Tensorflow exposes 'tf.__version__'. Can the Keanu version could be baked into releases and made accessible by a similar method?

As an alternative we are going to have the version hardcoded. However this will rely on it being updated each time Keanu is updated.

**Comment by GeorgeNash** [comment]
You should be able to get this from the `version` info when installing the package from maven / gradle.

https://search.maven.org/artifact/io.improbable/keanu/0.0.16/jar
