### ISSUE TITLE
Searching vertices by ID in network

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#341]
**Is your feature request related to a problem? Please describe.**
When debugging graphs with >100 vertices it can get a bit tricky to inspect individual vertices (e.g. by sampling). Sometimes I found myself auto-generating IDs for vertices ('input_vertex_1', 'input_vertex_2', 'parameter_1', etc.) and it would be super useful to just retrieve all vertices with an ID using a wildcard search.

**Describe the solution you'd like**
A method in the `BayesianNetwork` class that returns a list of vertices that match a search string.
```
List<Vertex> search(String searchString)
```

**Comment by wesleyw72** [comment]
I think you mean labels rather than IDs. If that is the case, we have work planned to add this functionality.

**Comment by GeorgeNash** [comment]
On the backlog - will let you know once merged in
