### ISSUE TITLE
Converting VertexSamples to DoubleTensor

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#342]
At the moment it is quite hard to work with samples coming from MH and NUTS because they are in the `NetworkSamples` (or `VertexSamples`) format. `VertexSamples` has an `asList()` method. Can we please also have a `asTensor` method?

**Comment by GeorgeNash** [comment]
You can get a `List<DoubleTensor>` of the samples by doing: `List<DoubleTensor> samples = networkSamples.getDoubleTensorSamples(probabilityA).asList();`

What behaviour would you want from an `asTensor` method? Let's say you have a vertex of shape `2x2` and you've taken `n` samples. Would `asTensor` return a tensor of shape `2x2xn`?

**Comment by GeorgeNash** [comment]
Merged and closing
