### ISSUE TITLE
Custom proposal distributions for metropolis hastings

### ISSUE THREAD

**Issue by river-fish** [improbable-research/keanu#354]
**Is your feature request related to a problem? Please describe.**
My metropolis hastings samples are mixing poorly and I'd like to explore the effect of using a lower variance proposal distribution than my priors for some vertices

**Describe the solution you'd like**
The option to control proposal dist choice separately to the prior when calling 

sampling.sample(net=net, 
                            sample_from=net.get_latent_vertices(), 
                            algo='metropolis',
                            draws=2000)

**Describe alternatives you've considered**
Using NUTS so step size is adaptive - this currently not helping, so would be great to have more control so can investigate behaviour of samplers

**Additional context**
Implementing a hierarchical linear model similar to this http://www.sanjogmisra.com/blog/stan/

**Comment by GeorgeNash** [comment]
You have the `POWER` in the Java world to define a gaussian proposal distribution like so:

```
        ProposalDistribution proposalDistribution = new GaussianProposalDistribution(DoubleTensor.scalar(1.));

        MetropolisHastings metropolisHastings = MetropolisHastings.builder()
            .proposalDistribution(proposalDistribution)
            .build();
```

Not currently exposed in the Python API - will add a JIRA for that.

Is a Gaussian proposal sufficient? What are you looking for?

**Comment by migwellian** [comment]
In progress for Python (SOL-2984)

**Comment by christophernorth** [comment]
We now have the ability from the Python API to:
a) use a custom proposal distribution for MetropolisHastings
b) Change NUTs parameters.  Closing this issue - let us know if you hit issues with the new APIs!
