### ISSUE TITLE
UniformVertex upper bound is not inclusive

### ISSUE THREAD

**Issue by CharlieCrisp** [improbable-research/keanu#380]
**Describe the bug**
The UniformVertex allows you to specify upper and lower bounds but the upper bound is exclusive and doing a logProb() at this value will give -Infinity.

**To Reproduce**
```java
UniformVertex vertex = new UniformVertex(0.0, 1.0);
vertex.setValue(1.0);
vertex.logProbAtValue();
```

**Expected behavior**
Upper bound should be inclusive

**Comment by GeorgeNash** [comment]
This has been intentionally done to make it easy to map from RNG's. @gordoncaleb has opinions on this so I'll loop him back in when he's back from holiday.
