### ISSUE TITLE
Dotsaver only saves first set of union of unconnected vertices

### ISSUE THREAD

**Issue by ViRb3** [improbable-research/keanu#447]
A list contains sets of vertices. The sets are not immediately connected to each other, but will be further in the program logic. To apply them to a bayesian network, which accept only one set of vertices, their union is created.

**Expected behavior:**
Dotsaver should save the full bayesian network containing all sets of vertices.

**Actual behavior:**
Dotsaver only saves the first connected set of vertices, ignoring the rest.
```
digraph BayesianNetwork {
<112> -> <113> [label=max]
<148> -> <149> [label=right]
<150> -> <151> [label=right]
<111> -> <113> [label=min]
<113> -> <149> [label=left]
<113> -> <151> [label=left]
113[label="UniformIntVertex"]
148[label="0"]
149[label="EqualsVertex"]
150[label="1"]
151[label="EqualsVertex"]
111[label="0"]
112[label="2"]
}
```

![image](https://user-images.githubusercontent.com/2650170/51440272-4b588580-1cbd-11e9-9a0f-a807fae18dcd.png)

**Code:**
```kotlin
fun bug_a() {
    val cards = ArrayList<IntegerVertex>()
    for (i in 0 until 10) {
        cards.add(UniformIntVertex(0, 2)) // player 0 or 1
    }
    for (i in 0 until 5) {
        cards[i].observe(0) // ai's card
    }
    for (card in cards) {
        for (i in 0 until 2) {
            card.equalTo(ConstantVertex.of(i))
        }
    }
    val dotsaver = DotSaver(BayesianNetwork(cards))
    dotsaver.save(FileOutputStream(File("Dotfile")), false)
}
```

**Comment by christophernorth** [comment]
Hey - agreed the behaviour here leaves a little to be desired!  The API surrounding the BayesianNetwork object is a little confusing at the moment, and will likely change a bit in future, but in general we'd recommend the following guidelines to avoid issues such as this:
1) Initialise a Bayesian Network using the output from getConnectedGraph() from a Vertex, and in particular only pass connected graphs to the BayesNet constructor (so don't manually create a union of two graphs in one BayesNet)
2) Treat BayesNets as Immutable - ie if you make a change to a graph after instantiating a BayesNet - throw the old one away and create a new one.

As I say, the BayesNet API is likely to change in future to explicitly make this sort of use case unsupported, so for now I'm going to close this issue.  Let me know if you have any more questions!
