### ISSUE TITLE
Build broken on windows:

### ISSUE THREAD

**Issue by chris-major-improbable** [improbable-research/keanu#48]
When building on windows (e.g. new clone of master, followed by gradle build) I get a build faliure with errors such as:

:keanu-project:javadocC:\Users\chris.major\Documents\keanu\keanu-project\src\main\java\io\improbable\keanu\algorithms\mcmc\Hamiltonian.java:140: error: unmappable character for encoding Cp1252

Even when viewed in github it looks like the file encoding isn't correct.

**Comment by gordoncaleb** [comment]
This is addressed in in PR #52. I'll let you know when it's been merged. We will also add a windows build to CI to address this happening in the future.

**Comment by gordoncaleb** [comment]
Now building with Windows using Appveyor. Closing the issue.
