### ISSUE TITLE
`set_and_cascade` not working?

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#515]
When running `set_and_cascade()` on the inputs of a Gaussian it's values don't get updated. Perhaps I am misunderstanding what `set_and_cascade()` does, so I added two examples below to show what's going on.

This works:
```
import keanu as kn
a = kn.vertex.Gaussian(0., 1.)
b = kn.vertex.Gaussian(0., 1.)
c = a + b
a.set_and_cascade(10.)
c.get_value() == a.get_value() + b.get_value()
```
but this doesn't:
```
import keanu as kn
a = kn.vertex.Gaussian(0., 1.)
b = kn.vertex.Gaussian(0., 1.)
c = kn.vertex.Gaussian(a + b, 1.)
a.set_and_cascade(10.)
c.get_value() == a.get_value() + b.get_value()
```
I discovered this because `MetropolisHastings` didn't seem to update the values of latent vertices in my graph. And btw, I'm using v0.0.20.

**Comment by icantsayrural** [comment]
`set_and_cascade` causes a cascading change of values if any of the children vertices are non-probabilistic. Since `c` is probabilistic, cascading its parents values to it would require sampling. If you want to know the value of `c` after the cascade, you can do `c.sample()`.
