### ISSUE TITLE
[Question] Are SonarQube fixes welcome?

### ISSUE THREAD

**Issue by dvmarcilio** [improbable-research/keanu#565]
Hello,

I'm willing to contribute with fixes for some SonarQube rules. Is that something of interest for the project? If yes, should I just open pull requests?

Thanks!

**Comment by christophernorth** [comment]
Hey - thanks for your interest, and yeah, feel free to open a PR for any fixes!

**Comment by dvmarcilio** [comment]
Thanks for the fast answer! Expect some PRs coming soon.
