### ISSUE TITLE
Improve error message when trying to use variational methods on a non-continuous network

### ISSUE THREAD

**Issue by dmculley** [improbable-research/keanu#91]
**Is your feature request related to a problem? Please describe.**
Obviously trying to use GradientOptimizer on a graph with Poissons in is silly but it would be good to have reliable error messaging as a safety net.

**Comment by christophernorth** [comment]
An UnsupportedOperationException will now be reliably thrown if you try and use a gradient optimiser on a graph containing discrete Vertices.
